### ISSUE TITLE
Service works but generates errors in logs

### ISSUE THREAD

**Issue by cryoff** [devforth/OnLogs#3]
Hello!
I am running OnLogs as a service using `docker compose`.
It runs nicely, everything works however logs of `onlogs` show errors:

```
....

    /backend/app/daemon/daemon.go:176 +0x496                                                                  
 github.com/devforth/OnLogs/app/routes.GetHosts({0x82d8d8, 0xc00007f0a0}, 0xc000588b18?)                      
    /backend/app/routes/routes.go:257 +0x69                                                                   
 net/http.HandlerFunc.ServeHTTP(0x440740?, {0x82d8d8?, 0xc00007f0a0?}, 0x6423da?)                             
    /usr/local/go/src/net/http/server.go:2136 +0x29                                                           
 net/http.(*ServeMux).ServeHTTP(0xa7d520?, {0x82d8d8, 0xc00007f0a0}, 0xc008b07500)                            
    /usr/local/go/src/net/http/server.go:2514 +0x142                                                          
 net/http.serverHandler.ServeHTTP({0xc008296f30?}, {0x82d8d8?, 0xc00007f0a0?}, 0x6?)                          
    /usr/local/go/src/net/http/server.go:2938 +0x8e                                                           
 net/http.(*conn).serve(0xc000002510, {0x82e330, 0xc000578180})                                               
    /usr/local/go/src/net/http/server.go:2009 +0x5f4                                                          
 created by net/http.(*Server).Serve in goroutine 1                                                           
    /usr/local/go/src/net/http/server.go:3086 +0x5cb                                                          
 2024/02/23 12:56:55 http: panic serving 95.90.209.249:42058: resource temporarily unavailable                
 goroutine 1557 [running]:                                                                                    
 net/http.(*conn).serve.func1()                                                                               
    /usr/local/go/src/net/http/server.go:1868 +0xb9                                                           
 panic({0x74cc40?, 0xa0d630?})                                                                                
    /usr/local/go/src/runtime/panic.go:920 +0x270                                                             
 github.com/devforth/OnLogs/app/daemon.GetContainersList()                                                    
    /backend/app/daemon/daemon.go:176 +0x496                                                                  
 github.com/devforth/OnLogs/app/routes.GetHosts({0x82d8d8, 0xc000560ee0}, 0xc0001bdb18?)                      
    /backend/app/routes/routes.go:257 +0x69                                                                   
 net/http.HandlerFunc.ServeHTTP(0x440740?, {0x82d8d8?, 0xc000560ee0?}, 0x6423da?)                             
    /usr/local/go/src/net/http/server.go:2136 +0x29                                                           
 net/http.(*ServeMux).ServeHTTP(0xa7d520?, {0x82d8d8, 0xc000560ee0}, 0xc0004e9c00)                            
    /usr/local/go/src/net/http/server.go:2514 +0x142                                                          
 net/http.serverHandler.ServeHTTP({0xc0003fc090?}, {0x82d8d8?, 0xc000560ee0?}, 0x6?)                          
    /usr/local/go/src/net/http/server.go:2938 +0x8e                                                           
 net/http.(*conn).serve(0xc007a05200, {0x82e330, 0xc000578180})                                               
    /usr/local/go/src/net/http/server.go:2009 +0x5f4                                                          
 created by net/http.(*Server).Serve in goroutine 1                                                           
    /usr/local/go/src/net/http/server.go:3086 +0x5cb 
...
```

**Comment by LbP22** [comment]
Fixed, you can check it

**Comment by ivictbor** [comment]
@cryoff Please update docker image to latest or 1.04 version of https://hub.docker.com/r/devforth/onlogs

**Comment by cryoff** [comment]
Thank you, I am testing 1.0.4 now!
